package appinventor.ai_raghav1687.golfball;

/* This class is generated by JADX */
public final class R {

    public static final class drawable {
        public static final int ya = 2130837504;
    }

    public static final class anim {
        public static final int fadein = 2130903040;
        public static final int fadeout = 2130903041;
        public static final int hold = 2130903042;
        public static final int slide_enter = 2130903043;
        public static final int slide_enter_reverse = 2130903044;
        public static final int slide_exit = 2130903045;
        public static final int slide_exit_reverse = 2130903046;
        public static final int slide_v_enter = 2130903047;
        public static final int slide_v_enter_reverse = 2130903048;
        public static final int slide_v_exit = 2130903049;
        public static final int slide_v_exit_reverse = 2130903050;
        public static final int zoom_enter = 2130903051;
        public static final int zoom_enter_reverse = 2130903052;
        public static final int zoom_exit = 2130903053;
        public static final int zoom_exit_reverse = 2130903054;
    }
}
